## **ETL archivo Business**

### Librerias Necesarias

In [1]:
!pip install fastparquet

Collecting fastparquet
  Downloading fastparquet-2023.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 9.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from fastparquet) (1.5.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from fastparquet) (1.23.5)
Collecting cramjam>=2.3 (from fastparquet)
  Downloading cramjam-2.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 16.2 MB/s eta 0:00:00
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet) (2023.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet) (23.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.0->fastparquet) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=1.5.0->fastparquet) (1.16.0)
Installing collected packages: cramjam, fastparquet
Successfully installed cramjam-2.7.0 fastparquet-2023.8.0

In [3]:
import pandas as pd
import numpy as np
import fastparquet

### Importar archivo

In [4]:
ruta = '/content/yelp_business.parquet'
df = pd.read_parquet(ruta)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       150346 non-null  object
 3   city          150346 non-null  object
 4   state         150343 non-null  object
 5   postal_code   150346 non-null  object
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  int64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 17.2+ MB

### 1. Filtrado por rubro "SteakHouses"

In [5]:
#Creamos una mascara
mask = df['categories'].str.contains('Steakhouses',case = False) == True
df_steak = df[mask]

In [6]:
df_steak.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506 entries, 22 to 150276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   1506 non-null   object
 1   name          1506 non-null   object
 2   address       1506 non-null   object
 3   city          1506 non-null   object
 4   state         1506 non-null   object
 5   postal_code   1506 non-null   object
 6   latitude      1506 non-null   float64
 7   longitude     1506 non-null   float64
 8   stars         1506 non-null   float64
 9   review_count  1506 non-null   int64
 10  is_open       1506 non-null   int64
 11  attributes    1496 non-null   object
 12  categories    1506 non-null   object
 13  hours         1400 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 176.5+ KB

In [7]:
#Revisamos
df_steak.sample(3)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
82423,kaC8SY5tUizqrTXrB8VNdg,Whitemarsh Valley Inn,474 Germantown Pike,Lafayette Hill,TN,19444,40.089496,-75.257142,3.0,27,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Lounges, Event Planning & Services, Restaurant...","{'Friday': '11:30-0:30', 'Monday': '0:0-0:0', ..."
96098,HSY2c6NbngjDHkuwZi7C2Q,Tequila's,"3736 Annex Ave, Ste 107",Nashville,IN,37209,36.141472,-86.882156,4.0,174,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Food Court, Steakhouses, Seafood,...","{'Friday': '11:0-22:0', 'Monday': '11:0-22:0',..."
122654,cR_5wHI9bMpcVma8OH5dsQ,Mere Bulles,5201 Maryland Way,Brentwood,AZ,37027,36.033978,-86.803731,4.0,326,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","American (Traditional), Salad, Venues & Event ...","{'Friday': '11:0-20:30', 'Monday': '0:0-0:0', ..."

In [8]:
#Reiniciamos Indices
df_steak.reset_index(drop=True, inplace=True)
#Revisamos
df_steak.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,6625 E 82nd St,Indianapolis,PA,46250,39.904320,-86.053080,4.0,20,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Steakhouses, Asian Fusion, Restaurants","{'Friday': '11:0-21:0', 'Monday': '11:0-21:0',..."
1,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,IL,62002,38.896563,-90.186203,3.0,94,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Specialty Food, Steakhouses, Food...","{'Friday': '16:0-22:0', 'Monday': '0:0-0:0', '..."
2,aCDY7vXYMs54EbYuQScsnQ,39 North Taproom & Grill,110 S MacDade Blvd,Glenolden,DE,19036,39.903697,-75.294981,4.5,25,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","American (Traditional), Sports Bars, Restauran...","{'Friday': '11:0-2:0', 'Monday': '0:0-0:0', 'S..."
3,CtMEJxpVMlNzFpB4PtFjfA,Aussie Grill,25340 Sierra Center Blvd,Lutz,AZ,33559,28.192191,-82.396367,4.0,75,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, American (New), Burgers, Fast Foo...","{'Friday': '11:0-21:0', 'Monday': '0:0-0:0', '..."
4,Dtuf4vD0znzwJW9vk3iTNw,Tomo Japanese Steakhouse and Sushi Bar,"7411 N Keystone Ave, Ste A",Indianapolis,MO,46240,39.888725,-86.121213,4.0,246,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Steakhouses, Restaurants, Sushi Bars, Japanese","{'Friday': '16:30-22:30', 'Monday': '0:0-0:0',..."

### 2. Filtramos las columnas necesarias

In [9]:
print(df_steak.columns.tolist())

['business_id', 'name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'attributes', 'categories', 'hours']

In [10]:
#Definir las columnas que se usarán
columnas = ['business_id', 'name', 'address', 'city', 'latitude', 'longitude', 'stars', 'review_count', 'is_open', 'categories']

In [11]:
#Filtramos
df_steak = df_steak[columnas]

In [12]:
df_steak.head()

,business_id,name,address,city,latitude,longitude,stars,review_count,is_open,categories
0,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,6625 E 82nd St,Indianapolis,39.904320,-86.053080,4.0,20,1,"Steakhouses, Asian Fusion, Restaurants"
1,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,38.896563,-90.186203,3.0,94,1,"Restaurants, Specialty Food, Steakhouses, Food..."
2,aCDY7vXYMs54EbYuQScsnQ,39 North Taproom & Grill,110 S MacDade Blvd,Glenolden,39.903697,-75.294981,4.5,25,1,"American (Traditional), Sports Bars, Restauran..."
3,CtMEJxpVMlNzFpB4PtFjfA,Aussie Grill,25340 Sierra Center Blvd,Lutz,28.192191,-82.396367,4.0,75,1,"Restaurants, American (New), Burgers, Fast Foo..."
4,Dtuf4vD0znzwJW9vk3iTNw,Tomo Japanese Steakhouse and Sushi Bar,"7411 N Keystone Ave, Ste A",Indianapolis,39.888725,-86.121213,4.0,246,1,"Steakhouses, Restaurants, Sushi Bars, Japanese"

### 3. Tratamos nulos y duplicados

In [13]:
# Muestra la cantidad de valores nulos en cada columna
null_counts = df_steak.isnull().sum()
print(null_counts)

business_id     0
name            0
address         0
city            0
latitude        0
longitude       0
stars           0
review_count    0
is_open         0
categories      0
dtype: int64

In [14]:
df_steak.drop_duplicates(inplace=True)

In [15]:
df_steak.dropna(inplace=True)

In [16]:
df_steak.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506 entries, 0 to 1505
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   1506 non-null   object
 1   name          1506 non-null   object
 2   address       1506 non-null   object
 3   city          1506 non-null   object
 4   latitude      1506 non-null   float64
 5   longitude     1506 non-null   float64
 6   stars         1506 non-null   float64
 7   review_count  1506 non-null   int64
 8   is_open       1506 non-null   int64
 9   categories    1506 non-null   object
dtypes: float64(3), int64(2), object(5)
memory usage: 129.4+ KB

### 4. Tratamos datos

In [17]:
df_steak.head()

,business_id,name,address,city,latitude,longitude,stars,review_count,is_open,categories
0,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,6625 E 82nd St,Indianapolis,39.904320,-86.053080,4.0,20,1,"Steakhouses, Asian Fusion, Restaurants"
1,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,38.896563,-90.186203,3.0,94,1,"Restaurants, Specialty Food, Steakhouses, Food..."
2,aCDY7vXYMs54EbYuQScsnQ,39 North Taproom & Grill,110 S MacDade Blvd,Glenolden,39.903697,-75.294981,4.5,25,1,"American (Traditional), Sports Bars, Restauran..."
3,CtMEJxpVMlNzFpB4PtFjfA,Aussie Grill,25340 Sierra Center Blvd,Lutz,28.192191,-82.396367,4.0,75,1,"Restaurants, American (New), Burgers, Fast Foo..."
4,Dtuf4vD0znzwJW9vk3iTNw,Tomo Japanese Steakhouse and Sushi Bar,"7411 N Keystone Ave, Ste A",Indianapolis,39.888725,-86.121213,4.0,246,1,"Steakhouses, Restaurants, Sushi Bars, Japanese"

- Reorganizamos y separamos columnas

In [18]:
# Función lambda para reorganizar las categorías
reorganizar = lambda x: ', '.join(sorted(x.split(', '), key=lambda s: s != 'Steakhouses'))

# Aplicar la función lambda a la columna 'categories'
df_steak['categories'] = df_steak['categories'].apply(reorganizar)

# Separar las categorías en una nueva columna 'Categoria' y las demás en 'Subcategoria'
df_steak['categorie'] = df_steak['categories'].str.split(', ').str[0]
df_steak['subcategorie'] = df_steak['categories'].str.split(', ').str[1:].apply(', '.join)

In [19]:
df_steak.head()

,business_id,name,address,city,latitude,longitude,stars,review_count,is_open,categories,categorie,subcategorie
0,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,6625 E 82nd St,Indianapolis,39.904320,-86.053080,4.0,20,1,"Steakhouses, Asian Fusion, Restaurants",Steakhouses,"Asian Fusion, Restaurants"
1,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,38.896563,-90.186203,3.0,94,1,"Steakhouses, Restaurants, Specialty Food, Food...",Steakhouses,"Restaurants, Specialty Food, Food, Italian, Pi..."
2,aCDY7vXYMs54EbYuQScsnQ,39 North Taproom & Grill,110 S MacDade Blvd,Glenolden,39.903697,-75.294981,4.5,25,1,"Steakhouses, American (Traditional), Sports Ba...",Steakhouses,"American (Traditional), Sports Bars, Restauran..."
3,CtMEJxpVMlNzFpB4PtFjfA,Aussie Grill,25340 Sierra Center Blvd,Lutz,28.192191,-82.396367,4.0,75,1,"Steakhouses, Restaurants, American (New), Burg...",Steakhouses,"Restaurants, American (New), Burgers, Fast Food"
4,Dtuf4vD0znzwJW9vk3iTNw,Tomo Japanese Steakhouse and Sushi Bar,"7411 N Keystone Ave, Ste A",Indianapolis,39.888725,-86.121213,4.0,246,1,"Steakhouses, Restaurants, Sushi Bars, Japanese",Steakhouses,"Restaurants, Sushi Bars, Japanese"

In [20]:
# Eliminar la columna original 'categories'
df_steak.drop('categories', axis=1, inplace=True)

In [21]:
df_steak.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506 entries, 0 to 1505
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   1506 non-null   object
 1   name          1506 non-null   object
 2   address       1506 non-null   object
 3   city          1506 non-null   object
 4   latitude      1506 non-null   float64
 5   longitude     1506 non-null   float64
 6   stars         1506 non-null   float64
 7   review_count  1506 non-null   int64
 8   is_open       1506 non-null   int64
 9   categorie     1506 non-null   object
 10  subcategorie  1506 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 141.2+ KB

In [22]:
df_steak.sample(5)

,business_id,name,address,city,latitude,longitude,stars,review_count,is_open,categorie,subcategorie
499,6VPD2WrgtD8h5UzjqaUnFA,Delmonico's Steakhouse,4200 City Ave,Philadelphia,40.004379,-75.218198,3.0,49,0,Steakhouses,"Hotels & Travel, Restaurants, Event Planning &..."
367,YaxZ-Yw0PfFMG9w0XA3kGQ,Drink and Eat on Citrus,5608 Citrus Blvd,Harahan,29.964538,-90.194742,4.0,26,0,Steakhouses,"Seafood, Soul Food, Restaurants"
704,tEHgpkQT50Z-M0XafS8YoQ,Water Oak Grill,"201 Main St, Ste 100",Safety Harbor,27.991062,-82.689255,4.0,117,1,Steakhouses,"Restaurants, Seafood, American (New)"
1179,04lEB3_tQGky8dq5kCa9Vg,Steak ’n Shake,1501 E 86th St,Indianapolis,39.912066,-86.134577,2.5,49,1,Steakhouses,"Burgers, Restaurants, Breakfast & Brunch, Amer..."
1236,8LnbTdnHn8See0nS9rfPvw,Applebee's Grill + Bar,3219 Street Rd,Bensalem,40.117898,-74.958859,3.0,73,1,Steakhouses,"Nightlife, Bars, Restaurants, Sports Bars, Bur..."

-------------------------

- Cambiar nombres de columnas

In [51]:
#Renombramos columnas
nombre_columnas = {
    'business_id': 'id_negocio',
    'name': 'nombre',
    'address': 'direccion',
    'city': 'ciudad',
    'state': 'estado',
    'latitude': 'latitud',
    'longitude': 'longitud',
    'stars': 'puntuacion',
    'review_count': 'cantidad_reviews',
    'is_open': 'abierto',
    'categorie': 'categoria',
    'subcategorie': 'subcategoria'
}

In [52]:
df_steak.rename(columns=nombre_columnas, inplace = True)

In [53]:
df_steak.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1506 entries, 0 to 1505
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_negocio        1506 non-null   object
 1   nombre            1506 non-null   object
 2   direccion         1506 non-null   object
 3   ciudad            1506 non-null   object
 4   estado            1506 non-null   object
 5   latitud           1506 non-null   float64
 6   longitud          1506 non-null   float64
 7   puntuacion        1506 non-null   float64
 8   cantidad_reviews  1506 non-null   int64
 9   abierto           1506 non-null   int64
 10  categoria         1506 non-null   object
 11  subcategoria      1506 non-null   object
dtypes: float64(3), int64(2), object(7)
memory usage: 153.0+ KB

In [55]:
df_steak.sample(5)

,id_negocio,nombre,direccion,ciudad,estado,latitud,longitud,puntuacion,cantidad_reviews,abierto,categoria,subcategoria
1331,FmCxht0z_8C2DeVvdZEK5w,Applebee's Grill + Bar,2921 S Service Rd,Saint Charles,TN,38.784200,-90.527100,3.0,34,1,Steakhouses,"American (New), Nightlife, Chicken Wings, Amer..."
1045,h1N4EPorcu3DIol0hKE1rg,LongHorn Steakhouse,2055 N Dale Mabry Hwy,Tampa,FL,27.960909,-82.504840,2.5,15,0,Steakhouses,"American (Traditional), Restaurants"
1443,woTZpX92uByUgliPrh39Mg,Ocean Prime,124 S 15th St,Philadelphia,AZ,39.950174,-75.165934,4.0,513,1,Steakhouses,"Cocktail Bars, American (New), Bars, Restauran..."
705,_10m_xRpfqqnj9jvUUIqjA,Applebee's Grill + Bar,70 Buckwalter Rd,Limerick,LA,40.198026,-75.525558,2.0,45,1,Steakhouses,"Bars, Restaurants, Chicken Wings, Sports Bars,..."
983,7qQuFv3wEHneQ1JLpfh4NA,Applebee's Grill + Bar,7995 113th St,Seminole,PA,27.844811,-82.794700,2.0,39,1,Steakhouses,"Burgers, American (New), Bars, Nightlife, Spor..."

- Se revisa las ciudades para determinar las mas recurrentes

In [59]:
#Revisamos CIUDADES unicas
ciudad = df_steak['ciudad'].unique()
print(ciudad)

['Indianapolis' 'Alton' 'Glenolden' 'Lutz' 'Virginia City' 'Marana'
 'Saint Louis' 'Edmonton' 'New Orleans' 'St. Louis' 'Boise' 'Philadelphia'
 'Saint Petersburg' 'Bensalem' 'Creve Coeur' 'Phoenixville' 'Nashville'
 'Des Peres' 'St. Petersburg' 'Port Richey' 'Meridian' 'Reno' 'Brandon'
 'Freeburg' 'Norristown' 'Dunedin' 'Sicklerville' 'Tampa' 'Abington'
 'Clearwater' 'West Chester' 'Plainfield' 'New Castle' 'Madison'
 'Saint Pete Beach' 'St Petersburg' 'Hendersonville' 'Mt. Juliet'
 'Riverview' 'Shamong' 'Springfield' 'Tucson' 'Pennsville' 'Spring Hill'
 'Greenbrier' 'Glen Mills' 'Odessa' 'Zionsville' 'King Of Prussia'
 'Franklin' 'Oaklyn' 'Kenner' 'Collingswood' 'Hazelwood' 'Royersford'
 'St Charles' 'Smyrna' 'Wayne' 'Deptford' 'Drexel Hill' 'Langhorne'
 'Apollo Beach' 'Temple Terrace' 'Metairie' 'Plymouth Meeting' 'Seminole'
 'Plant City' 'Swansea' 'Avon' 'Mount Juliet' 'Goleta' 'Wilmington'
 'Warminster' 'Sparks' 'Santa Barbara' 'Indian Rocks Beach' 'St Louis'
 'Newtown' 'Mount Laurel' 'Fairview Heights' 'Fairless Hills' 'Harahan'
 'Fishers' 'Pinellas Park' 'North Wales' 'Conshohocken' 'Bridgeton'
 'Edwardsville' 'Marlton' 'Newark' 'Lithia' 'Carmel' 'Broomall'
 'Southampton' 'Montgomeryville' 'Hatboro' 'Brentwood' 'Greenwood'
 'Cherry Hill' 'Brownsburg' 'Garden City' 'King of Prussia' 'Swedesboro'
 'Collegeville' 'Exton' 'Lester' 'Lansdale' 'Arnold' 'Tarpon Springs'
 'Harvey' 'Shiloh' "O'Fallon" 'Media' 'Newtown Square' 'West Berlin'
 'Ambler' 'St Albert' 'Doylestown' 'Croydon' 'St. Albert' 'Ivyland'
 'Jenkintown' 'Marrero' 'Granite City' 'Collinsville' 'Lansdowne'
 'Prospect Park' 'Hermitage' 'Trenton' 'Glassboro' 'Westampton' 'Valrico'
 'Boyertown' 'Kennett Square' 'New Port Richey' 'Havertown' 'Meridian '
 'Gulfport' 'Radnor' 'Sunset Hills' 'St. Charles' 'Antioch' 'Horsham'
 'Morrisville' 'Eagle' 'Carrollwood' 'Sappington' 'Mascoutah' 'Fenton'
 'Saint Charles' 'Warrington' 'Madeira Beach' 'Concord Township'
 'Safety Harbor' 'New Hope' 'Hockessin' 'Wesley Chapel' 'Maplewood'
 'Bala Cynwyd' 'Lionville' 'Ballwin' 'St. Pete Beach' 'Williamstown'
 'Turnersville' 'Waterloo' 'Glendora' 'Somerdale' 'Medford' 'Zephyrhills'
 'Tarpon springs' 'O Fallon' 'Colmar' 'Gallatin' 'East Norriton' 'Yardley'
 'Jefferson' 'Largo' 'Pottstown' 'Ewing' 'Franklinville' 'Trinity'
 'Carpinteria' 'Sherwood Park' 'Feasterville Trevose' 'Florissant' 'Vail'
 'Toughkenamon' 'Burlington' 'Palm Harbor' 'Lindenwold' 'Gulph Mills'
 'Gretna' 'St Pete Beach' 'Goodlettsville' 'North Redington Beach'
 'Upper Darby' 'Dade City' 'Clearwater Beach' 'Skippack' 'Castleton'
 'Gilbertsville' 'Woodbury' 'Belleair Bluffs' 'Limerick' 'Brooklawn'
 'Paoli' 'Terrytown' 'White House' 'Hudson' 'Pennsauken' 'Oro Valley'
 'Morton' 'Richmond Heights' 'Hernando Beach' 'Bordentown'
 'Gloucester City' 'Gibbsboro' 'Folsom' 'Lafayette Hill' 'Audubon'
 'Treasure Island' 'Blue Bell' 'Merion Station' 'Sewell' 'Chadds Ford'
 'Huntingdon Valley' 'Hamilton' 'Haddonfield' 'Bristol' 'Glen Carbon'
 'Clayton' 'Ardmore' 'High Ridge' 'Malvern' 'Glenmoore' 'Belleair Blf'
 'Wood River' 'Oldsmar' 'Lahaska' 'Nolensville' 'Godfrey' 'Parkside'
 'Saint John' 'Woodlyn' 'Frazer' 'Merchantville' 'Ridley Park' 'Holiday'
 'Moorestown' 'Camby' 'Downingtown' 'Voorhees' 'Pitman' 'Lambertville'
 'Blackwood' 'Maple Shade' 'Berwyn' 'Indian Shores' 'Maryland Heights'
 'South Pasadena' 'Haddon Heights' 'Tierra Verde' 'West Deptford'
 'Edgewater Park' 'Penndel' 'Speedway' 'Lawrence' 'Montecito'
 'Tierre Verde' 'Oaks' 'Harleysville' 'Tampa Palms' 'Mullica Hill' 'Aston'
 'Voorhees Township' 'Sun Valley' 'Jamison' 'Kirkwood' 'Barrington'
 'Bryn Mawr' 'Chester' 'Mooresville' 'Saint Albert' 'Violet'
 'Sellersville' 'Telford' 'Darby' 'Chalmette' 'Levittown' 'Richboro'
 'Thorndale' 'Saint Ann' 'Valley Park']

In [64]:
pd.set_option('display.max_rows', None)

In [73]:
#Revisamos CIUDADES unicas
ciudad_conteo = df_steak['ciudad'].value_counts()
lista_ciudades = ciudad_conteo.head(25)
lista_ciudades

Philadelphia        106
Indianapolis        105
Edmonton             79
Tampa                76
Nashville            74
Tucson               64
Saint Louis          42
New Orleans          37
Reno                 36
Clearwater           27
Boise                23
Santa Barbara        19
Saint Petersburg     17
Franklin             17
Wilmington           15
Cherry Hill          14
Metairie             14
Carmel               13
St. Petersburg       13
Brandon              13
St. Louis            12
King of Prussia      11
Meridian             11
Springfield          10
Alton                 9
Name: ciudad, dtype: int64

In [74]:
lista = lista_ciudades.index.to_list

In [75]:
lista

<bound method IndexOpsMixin.tolist of Index(['Philadelphia', 'Indianapolis', 'Edmonton', 'Tampa', 'Nashville',
       'Tucson', 'Saint Louis', 'New Orleans', 'Reno', 'Clearwater', 'Boise',
       'Santa Barbara', 'Saint Petersburg', 'Franklin', 'Wilmington',
       'Cherry Hill', 'Metairie', 'Carmel', 'St. Petersburg', 'Brandon',
       'St. Louis', 'King of Prussia', 'Meridian', 'Springfield', 'Alton'],
      dtype='object')>

In [ ]:
#estados que tenemos
estados_mas = [
    'Pennsylvania',
    'Indiana',
    'Florida',
    'Tennessee',
    'Arizona',
    'Missouri',
    'Alberta (Canadá)',
    'Louisiana',
    'Nevada',
    'Delaware',
    'Mississippi',
    'Texas'
    'Idaho',
    'California',
    'Kentucky'
]